name = "SLapSim"
uuid = "e544a80c-baf6-4293-8b37-459aefb38611"
version = "1.0.0-DEV"
authors = ["Richard <ciglanskyri@gmail.com> and contributors"]

[deps]
Compiler = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
HermiteInterpolation = "e59a9049-0778-4b41-b4a6-c75571210bee"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KML = "1284bf3a-1e3d-4f4e-a7a9-b9d235a28f35"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PCHIPInterpolation = "afe20452-48d1-4729-9a8b-50fb251f06cd"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RungeKutta = "fb486d5c-30a0-4a8a-8415-a8b4ace5a6f7"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
UnoSolver = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Compiler = "0.1.1"
ControlSystemsBase = "1.19.0"
DSP = "0.8"
Debugger = "0.7.15"
Dierckx = "0.5.4"
DiffEqDevTools = "2.48.0"
DifferentiationInterface = "0.7.10"
GLMakie = "0.13.4"
GeometricIntegrators = "0.15.1"
HermiteInterpolation = "1.0.0"
Infiltrator = "1.9.3"
Interpolations = "0.16"
Ipopt = "1.11.0"
JuMP = "1.29.1"
KML = "0.2.3"
LinearAlgebra = "1.11.0"
MathOptInterface = "1.46.0"
Optim = "1.13.3"
OrdinaryDiffEq = "6.102.1"
PCHIPInterpolation = "0.2.1"
Polynomials = "4.1.0"
PrettyPrinting = "0.4.2"
ProfileView = "1.10.2"
Proj = "1.9.0"
Revise = "3.9.0"
RungeKutta = "0.5.17"
SpecialPolynomials = "0.5.0"
Statistics = "1.11.1"
UnicodePlots = "3.8.1"
UnoSolver = "0.1.2"
Zygote = "0.7.10"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
